module.exports = {
    data: [{
        id: 1,
        firstName: 'Dmitry',
        lastName: 'Domanski',
        gender: 'male',
        maidenName: null,
        matrimonialStatus: 'm',
        birthDate: '06/10/1982',
        deathDate: null,
        parentId: 8,
    },
    {
        id: 4,
        firstName: 'Adam',
        lastName: 'Domanski',
        gender: 'male',
        maidenName: null,
        matrimonialStatus: 'k',
        birthDate: '06/10/2008',
        deathDate: null,
        parentId: 1,
    },
    {
        id: 8,
        firstName: 'Andrey',
        lastName: 'Domanski',
        gender: 'male',
        maidenName: null,
        matrimonialStatus: 'k',
        birthDate: '15/07/1960',
        deathDate: null,
        parentId: 9,
    },
    {
        id: 9,
        firstName: 'Victor',
        lastName: 'Domanski',
        gender: 'male',
        maidenName: null,
        matrimonialStatus: 'k',
        birthDate: '11/04/1932',
        deathDate: '2010',
        parentId: null,
    },
    {
        id: 3,
        firstName: 'Vera',
        lastName: 'Domanski',
        gender: 'female',
        maidenName: null,
        matrimonialStatus: 'k',
        birthDate: '23/10/2006',
        deathDate: null,
        parentId: 1,
    },
    {
        id: 5,
        firstName: 'Daniel',
        lastName: 'Domanski',
        gender: 'male',
        maidenName: null,
        matrimonialStatus: 'k',
        birthDate: '14/12/2009',
        deathDate: null,
        parentId: 1,
    },
    {
        id: 6,
        firstName: 'Roza',
        lastName: 'Domanski',
        gender: 'female',
        maidenName: null,
        matrimonialStatus: 'k',
        birthDate: '17/10/2017',
        deathDate: null,
        parentId: 1,
    },
    {
        id: 10,
        firstName: 'Konstantin',
        lastName: 'Domanski',
        gender: 'male',
        maidenName: null,
        matrimonialStatus: 'm',
        birthDate: '06/10/1982',
        deathDate: null,
        parentId: 8,
    },
    {
        id: 11,
        firstName: 'Anna',
        lastName: 'Domanski',
        gender: 'female',
        maidenName: null,
        matrimonialStatus: 'k',
        birthDate: '15/10/2012',
        deathDate: null,
        parentId: 10,
    },
    {
        id: 12,
        firstName: 'Gregory',
        lastName: 'Domanski',
        gender: 'male',
        maidenName: null,
        matrimonialStatus: 'k',
        birthDate: '15/01/2015',
        deathDate: null,
        parentId: 10,
    },
    ]
}

